version: "2"

run:
  timeout: 5m
  tests: false

linters:
  default: 'none'
  enable:
    - errcheck
    - gosec
    - misspell
    - unconvert
    - unparam
    - sloglint

  settings:
    errcheck:
      exclude-functions:
        - (*database/sql.DB).Close
        - (*database/sql.Rows).Close
        - (*database/sql.Tx).Rollback
        - (*database/sql.Stmt).Close
        - (*database/sql.Conn).Close
        - (*os.File).Close
        - (os).RemoveAll
        - (os).Remove
        - (os).Setenv
        - (os).Unsetenv
        - (os).Chdir
        - (os).MkdirAll
        - (fmt).Sscanf
    misspell:
      locale: US

  exclusions:
    rules:
      # G304: File inclusion via variable in tests is safe (test data)
      - path: '_test\.go'
        linters:
          - gosec
        text: "G304"
      # G306: File permissions 0644 in tests are acceptable (test fixtures)
      - path: '_test\.go'
        linters:
          - gosec
        text: "G306"
      # G304: Safe file reads from known JSONL and error paths
      - path: 'cmd/fbd/autoflush\.go|cmd/fbd/daemon_autostart\.go|cmd/fbd/doctor/fix/sync_branch\.go|cmd/fbd/doctor/git\.go|cmd/fbd/rename_prefix\.go|cmd/fbd/sync_merge\.go|internal/beads/beads\.go|internal/daemon/discovery\.go|internal/daemonrunner/sync\.go|internal/syncbranch/worktree\.go'
        linters:
          - gosec
        text: "G304"
      # G302/G306: Directory/file permissions 0700/0750 are acceptable
      - linters:
          - gosec
        text: "G302.*0700|G301.*0750"
      # G302/G306: JSONL files and error logs need 0644 for debugging/sharing
      - path: 'cmd/fbd/autoflush\.go|cmd/fbd/daemon\.go|cmd/fbd/daemon_sync_branch\.go|cmd/fbd/resolve_conflicts\.go|cmd/fbd/setup\.go|internal/daemon/registry\.go|internal/daemonrunner/daemon\.go|internal/git/worktree\.go'
        linters:
          - gosec
        text: "G306"
      # G306: Git hooks must be executable (0700)
      - path: 'cmd/fbd/init\.go'
        linters:
          - gosec
        text: "G306.*0700"
      # G204: Safe subprocess launches with validated arguments
      - path: 'cmd/fbd/daemon_autostart\.go|cmd/fbd/daemon_sync_branch\.go|cmd/fbd/doctor\.go|cmd/fbd/doctor/fix/sync_branch\.go|cmd/fbd/gate\.go|cmd/fbd/gate_discover\.go|cmd/fbd/jira\.go|cmd/fbd/migrate_sync\.go|cmd/fbd/show\.go|cmd/fbd/sync\.go|internal/git/worktree\.go|internal/syncbranch/worktree\.go'
        linters:
          - gosec
        text: 'G204'
      # G104: Deferred file closes - errors are non-critical
      - path: 'cmd/fbd/show\.go'
        linters:
          - gosec
        text: "G104.*Close"
      # G115: Safe integer conversions in backoff calculations
      - path: 'cmd/fbd/daemon_autostart\.go'
        linters:
          - gosec
        text: "G115"
      # G201: SQL with fmt.Sprintf using placeholders (IN clause expansion)
      - path: 'internal/storage/sqlite/(dependencies|batch_ops)\.go'
        linters:
          - gosec
        text: "G201"
      # errcheck: Ignore unchecked errors in test files for common cleanup patterns
      - path: '_test\.go'
        linters:
          - errcheck
        text: "Error return value of .*(Close|Rollback|RemoveAll|Setenv|Unsetenv|Chdir|MkdirAll|Remove|Write|SetReadDeadline|SetDeadline|Start|Stop).* is not checked"

      # unparam: Placeholder functions that may return errors in future implementation
      - path: 'cmd/fbd/jira\.go'
        linters:
          - unparam
        text: 'reimportConflicts|resolveConflictsByTimestamp'
      # unparam: readOnly param kept for API symmetry with fix/sqlite_open.go
      - path: 'cmd/fbd/doctor/sqlite_open\.go'
        linters:
          - unparam
        text: 'readOnly'
      # unparam: childrenMap return computed for future parent-child display
      - path: 'cmd/fbd/list\.go'
        linters:
          - unparam
        text: 'buildBlockingMaps.*childrenMap'
      # unparam: truncateID maxLen kept for readability
      - path: 'cmd/fbd/migrate\.go'
        linters:
          - unparam
        text: 'truncateID.*maxLen'
      # misspell: "cancelled" is intentional - matching GitHub API response values
      - path: 'cmd/fbd/gate\.go'
        linters:
          - misspell
        text: 'cancelled'

issues:
  uniq-by-line: true
